config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      get '/articles/index'
      get '/users/index'
      get '/charts/index'

      post '/articles/create'
      post '/users/create'
      post '/charts/create'
      
      get '/articles/:id', to: 'articles#show'
      get '/users/:id', to: 'users#show'
      get '/pictures/:id', to: 'pictures#show'
      get '/charts/:id', to: 'chart#show'

      delete '/articles/destroy/:id', to: 'articles#destroy'
      delete '/charts/destroy/:id', to: 'charts#destroy'
      
      resources :users, only: [:create, :show, :index]
      resources :articles, only: [:create, :show, :index, :destroy]
      resources :charts, only: [:create, :show, :index, :destroy]
    end
  end
  
  get '/login', to: 'sessions#new', as: 'login'
  delete '/logout', to: 'sessions#destroy', as: 'logout'
  post '/login', to: 'sessions#create'
  get '/signup', to: 'users#new', as: 'signup'
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :users do
    member do
      get :confirm_email
      post :toggle_verified
    end
  end
  resources :search, only: [:index]
  resources :sessions, only: [:new, :create, :destroy]
  root 'pages#home'
  
  resources :cabin_attachments
  resources :articles do
    member do
      post :toggle_pinned
    end
  end
  resources :comments
  resources :events
  resources :cabins
  resources :cabindates
  resources :galleries
  resources :rooms
  resources :room_messages
  resources :charts

  get '/articles', to: 'articles#index'
  get '/blog', to: 'articles#index'
  get '/users', to: 'users#index'
  get '/search', to: 'pages#search', as: 'search'
  get '/forms', to: 'pages#forms', as: 'forms'
  get '/bylaws', to: 'pages#bylaws', as: 'bylaws'
  get '/chartiable_gift', to: 'pages#charitable_gift', as: 'charitable_gift'
  get '/customs', to: 'pages#customs', as: 'customs'
  get '/history', to: 'pages#history', as: 'history'
  get '/membership', to: 'pages#membership', as: 'membership'
  get '/planned_giving', to: 'pages#planned_giving', as: 'planned_giving'
  get '/familyagreements', to: 'pages#familyagreements', as: 'familyagreements'
  get '/archives', to: 'pages#archives', as: 'archives'
  get '/committee_primer', to: 'pages#committee_primer', as: 'committee_primer'

  match '*path' => 'pages#home', via: :all

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
    helper_method :require_user
    before_action :require_user
    
    def index
        if params[:search]
            @articles = Article.where('lower(title) LIKE ? OR lower(content) LIKE ?', "%#{params[:search].downcase}%", "%#{params[:search].downcase}%")
            @cabins = Cabin.where('lower(name) LIKE ? OR lower(description) LIKE ?', "%#{params[:search].downcase}%", "%#{params[:search].downcase}%")
            @users = User.where('lower(firstname) LIKE ? OR lower(lastname) LIKE ? OR lower(username) LIKE ?', "%#{params[:search].downcase}%", "%#{params[:search].downcase}%", "%#{params[:search].downcase}%")
            @events = Event.where('lower(events) LIKE ? OR lower(description) LIKE ?', "%#{params[:search].downcase}", "%#{params[:search].downcase}%")
        end
    end

    private

        def search_params
            params.permit(:search)
        end
end

app/views/search/index.html.erb
<% if logged_in?  %>
    <div class="container">
        <% if logged_in? %>
            <section class="col-xs-12 col-sm-6 col-md-12">
            <hgroup class="mb20">
                <h1>Search Results</h1>
                <h2 class="lead"><strong class="text-danger"><%= @articles.length + @users.length + @cabins.length + @events.length %></strong> results were found for the search for <strong class="text-danger"><%= params[:search] %></strong></h2>								
            </hgroup>
            <% if params[:search] %>
                <% if @articles.any? %>
                    <p>Articles:</p>
                    <% @articles.each do |a| %>
                        <article class="search-result row">
                            <div class="col-xs-12 col-sm-12 col-md-2">
                                <ul class="meta-search">
                                    <li><span><%= a.created_at %></span></li>
                                    <li><span><%= a.user ? a.user.username : "Original Poster Deleted"%></span></li>
                                </ul>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-7 excerpet">
                                <h3><a href="#" title=""><%= link_to a.title, article_path(a) %></a></h3>
                                <p><%= sanitize(a.content.truncate(200, tags: %w(strong em p br div ul ol li))) %></p>						
                            </div>
                            <span class="clearfix borda"></span>
                        </article>
                    <% end %>
                <% end %>
                <br>
                <% if @events.any? %>
                    <p>Events:</p>
                    <% @events.each do |e| %>
                        <article class="search-result row">
                            <div class="col-xs-12 col-sm-12 col-md-2">
                                <ul class="meta-search">
                                    <li><span><%= "#{e.start_time} - #{e.end_time}" %></span></li>
                                    <li><span><%= e.user ? e.user.username : "Original Poster Deleted" %></span></li>
                                </ul>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-7 excerpet">
                                <h3><a href="#" title=""><%= link_to e.events, event_path(e) %></a></h3>
                                <p><%= sanitize(e.description.truncate(200, tags: %w(strong em p br div ul ol li))) %></p>						
                            </div>
                            <span class="clearfix borda"></span>
                        </article>
                    <% end %>
                <% end %>
                <br>
                <% if @users.any? %>
                    <p>Users:</p>
                    <% @users.each do |u| %>
                        <article class="search-result row">
                            <div class="col-xs-12 col-sm-12 col-md-2">
                                <ul class="meta-search">
                                    <li><span><%= u.created_at %></span></li>
                                    <li><span><%= u.username %></span></li>
                                </ul>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-7 excerpet">
                                <h3><a href="#" title=""><%= link_to "#{u.firstname} #{u.lastname}", user_path(u) %></a></h3>				
                            </div>
                            <span class="clearfix borda"></span>
                        </article>
                    <% end %>
                <% end %>
                <br>
                <% if @cabins.any? %>
                    <p>Cabins:</p>
                    <% @cabins.each do |c| %>
                        <article class="search-result row">
                            <div class="col-xs-12 col-sm-12 col-md-2">
                                <ul class="meta-search">
                                    <li><span><%= c.created_at %></span></li>
                                    <li><span><%= c.user ? c.user.username : "Original Poster Deleted"%></span></li>
                                </ul>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-7 excerpet">
                                <h3><a href="#" title=""><%= link_to c.name, cabin_path(c) %></a></h3>
                                <p><%= sanitize(c.description.truncate(200, tags: %w(strong em p br div ul ol li))) %></p>						
                            </div>
                            <span class="clearfix borda"></span>
                        </article>
                    <% end %>
                <% end %>
            <% else %>
                <p>Nothing found here</p>
            <% end %>
            </section>
        <% else %>
            <h1>You must be logged in to access search results.</h1>
        <% end %>
    </div>
<% else %>
  <p>Account not verified</p>
<% end %>