config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      get '/articles/index'
      get '/users/index'
      get '/charts/index'

      post '/articles/create'
      post '/users/create'
      post '/charts/create'
      
      get '/articles/:id', to: 'articles#show'
      get '/users/:id', to: 'users#show'
      get '/pictures/:id', to: 'pictures#show'
      get '/charts/:id', to: 'chart#show'

      delete '/articles/destroy/:id', to: 'articles#destroy'
      delete '/charts/destroy/:id', to: 'charts#destroy'
      
      resources :users, only: [:create, :show, :index]
      resources :articles, only: [:create, :show, :index, :destroy]
      resources :charts, only: [:create, :show, :index, :destroy]
    end
  end
  
  get '/login', to: 'sessions#new', as: 'login'
  delete '/logout', to: 'sessions#destroy', as: 'logout'
  post '/login', to: 'sessions#create'
  get '/signup', to: 'users#new', as: 'signup'
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :users do
    member do
      get :confirm_email
      post :toggle_verified
    end
  end
  resources :search, only: [:index]
  resources :sessions, only: [:new, :create, :destroy]
  root 'pages#home'
  
  resources :cabin_attachments
  resources :articles do
    member do
      post :toggle_pinned
    end
  end
  resources :comments
  resources :events
  resources :cabins
  resources :cabindates
  resources :galleries
  resources :rooms
  resources :room_messages
  resources :charts

  get '/articles', to: 'articles#index'
  get '/blog', to: 'articles#index'
  get '/users', to: 'users#index'
  get '/search', to: 'pages#search', as: 'search'
  get '/forms', to: 'pages#forms', as: 'forms'
  get '/bylaws', to: 'pages#bylaws', as: 'bylaws'
  get '/chartiable_gift', to: 'pages#charitable_gift', as: 'charitable_gift'
  get '/customs', to: 'pages#customs', as: 'customs'
  get '/history', to: 'pages#history', as: 'history'
  get '/membership', to: 'pages#membership', as: 'membership'
  get '/planned_giving', to: 'pages#planned_giving', as: 'planned_giving'
  get '/familyagreements', to: 'pages#familyagreements', as: 'familyagreements'
  get '/archives', to: 'pages#archives', as: 'archives'
  get '/committee_primer', to: 'pages#committee_primer', as: 'committee_primer'

  match '*path' => 'pages#home', via: :all

end

app/models/article.rb
class Article < ApplicationRecord
    extend FriendlyId
    self.per_page = 10
    
    has_many :comments, dependent: :destroy
    belongs_to :user

    mount_uploader :image, ImageUploader

    include Filterable
    
    accepts_nested_attributes_for :comments
    
    validates :title, presence: true, length: { maximum: 50 }
    validates :content, presence: true, length: { maximum: 50000 }
    validates :user_id, presence: true

    friendly_id :title, use: :slugged
end

app/controllers/api/v1/articles_controller.rb
class Api::V1::ArticlesController < ApplicationController

    def index
        article = Article.all.order(created_at: :desc)
        render json: article unless !logged_in?
    end

    def create
        if logged_in? 
            article = Article.create!(article_params) 
            if article
                render json: article 
            else
                render json: article.errors
            end
        else 
            return nil
        end
    end

    def show
        if article
            render json: article unless !logged_in?
        else
            render json: article.errors
        end
    end

    def destroy
        article&.destroy unless !logged_in?
        render json: { message: 'Post deleted!'}
    end

    private

    def article_params
        params.permit(:title, :content, :image, :pinned, :user_id)
    end

    def article
        @article ||= Article.find(params[:id])
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

before_action :set_article, only: [:edit, :update, :show, :destroy]
before_action :require_user
helper_method :current_user, :logged_in?, :require_user

def new
    @article = current_user.articles.build
end

def show
    user = session[:user_id]
    set_article
    @comment = Comment.new(article_id: @article.id)
    if @article
        @comments = @article.comments.paginate(page: params[:page]).order("created_at DESC")
    end
end

def index
    respond_to do |format|
        if params[:search]
            format.html { @articles = Article.where('lower(title) LIKE ? OR lower(content) LIKE ?', "%#{params[:search].downcase}%", "%#{params[:search].downcase}%").paginate(page: params[:page]) }
            format.json { render json: @articles }
        else
            format.html { @articles = Article.paginate(page: params[:page]).reorder("pinned DESC", "created_at DESC") }
            format.json { render json: @articles.errors, status: :unprocessable_entity}
        end
    end
end

def create
    @article = current_user.articles.new(article_params)
    respond_to do |format|
        if @article.save
            format.html { redirect_to article_path(@article), notice: "Article created" }
            format.json { render :show, status: :ok, location: @article}
        else
            flash.now[:error] = "Something went wrong! Try again soon"
            format.html { render :new }
            format.json { render json: @article.errors, status: :unprocessable_entity}
        end
    end
end

def update
    if current_user.admin?
        set_article
    else
        @article = current_user.articles.find(params[:id])
    end
    respond_to do |format|
        if @article.update(article_params)
            format.html { redirect_to article_path(@article), notice: "Article updated" } 
            format.json { render :show, status: :ok, location: @article}
        else
            format.html { render :edit}
            format.json { render json: @article.errors, status: :unprocessable_entity }
        end
    end
end

def toggle_pinned
    set_article
    @article.toggle(:pinned).save
    redirect_to articles_path
end

def edit
    @article = current_user.articles.friendly.find(params[:id])
end

def destroy
    @article = current_user.articles.friendly.find(params[:id])
    respond_to do |format|
        if @article.destroy
            format.html { redirect_to articles_path, notice: "Article was deleted" }
            format.json { head :no_content }
        else
            format.html { redirect_to articles_path }
            format.json { render json: @article.errors, status: :unprocessable_entity}
        end
    end
end

private

    def article_params
        params.require(:article).permit(:title, :content, :pinned, :image, :user_id, :search)
    end

    def set_article
        @article = Article.friendly.find(params[:id])
    end

    def comment_params
        params.permit(:content, :user_id, :article_id)
    end
end

app/views/articles/_comment.html.erb
<div class="comment card">
    <div class="comment card-body">
        <% @comments.each do |c| %>
            <% if c.user && c.user.username %>
                <span><em><small>Posted by: <strong><%= link_to c.user.username, user_path(c.user) %></strong> <%= time_ago_in_words(c.created_at) %> ago</small></em></span>
            <% else %>
                <span><em><small>Posted by: <strong><%= 'user not found' %></strong> <%= time_ago_in_words(c.created_at) %> ago</small></em></span>
            <% end %>
            <p><%= c.content.html_safe %> </p>
            <% if logged_in? && c.user_id == current_user.id %>
                <span class="UIbutton"><%= button_to comment_path(c), method: :delete, data: { confirm: "are you sure you want to delete this comment?" }, class: "btn btn-xs btn-danger pull-right" do %>
                    <i class="fa fa-trash" aria-hidden="true"></i>
                <% end %></span>
            <% end %>
        <% end %>
    </div>
</div>

app/views/articles/_form.html.erb
<div class="container form-container">
    <div class="article-form">
        <%= form_for @article do |f| %>
            <%= render 'layouts/error_messages', object: @article %>
            <div class="row">
                <div class="form-group">
                    <%= f.label :title %>
                    <%= f.text_field :title, placeholder: "50 Character Limit", autofocus: true, class: "form-control" %>
                </div>
            </div>
            <div class="row">
                <div class="form-group">
                    <%= f.label :content %>
                    <%= trix_editor :article, :content, required: true, placeholder: "limit: 10000 characters" %>
                </div>
            </div>
            <div class="row">
                <div class="form-group">
                    <%= f.label :image %>
                    <%= f.file_field :image, class: "form-control" %>
                </div>
            </div>
            <div class="row">
                <div class="form-group">
                    <%= f.submit class: "btn btn-primary mb-2" %>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/articles/edit.html.erb
<h1 align="center" class="section-title">Edit an Article</h1>
<%= render 'form' %>

app/views/articles/index.html.erb
<div class="container">
    <h1 class="section-title">Fishchat <%= link_to "write an article", new_article_path, class: "btn btn-success article-banner-action" %></h1>
    <% if notice %>
        <p class="alert alert-notice"><%= notice %></p>
    <% end %>
    <%= will_paginate @articles, renderer: BootstrapPagination::Rails %>
    <br><br>
    <% if @articles.any? %>
        <% @articles.each do |article| %>
            <div class="<%= article.pinned ? 'article-card-pinned' : 'article-card' %>">               
                <div class="<%= article.image? ? 'article card-body' : 'article card-body-no-image' %>">
                    <div class="col md-6">
                        <h4><%= link_to article.title, article_path(article), :class => "card-title" %></h4>
                        <small>
                            <p class="card-subtitle mb-2 text-muted">Created by: 
                                <%= article.user.username if article.user %>
                                <% if article.comments.any? %>
                                    <small><span class="comment-count">(<%= pluralize(article.comments.count, 'comment') %>)</span></small>
                                <% end %>
                            </p>
                        </small>
                        <p class="card-text"><%= sanitize(article.content.truncate(200, tags: %w(strong em p br div ul ol li))) %></p>
                    </div>
                    <% if article.image && article.image.url %>
                        <div class="col md-6">
                            <% if article.image && File.extname(article.image.url).downcase.in?(['.jpg','.jpeg','.gif','.png']) %>
                                <%= image_tag(article.image.url, alt: 'Image', :class => "pull-right article-image", id: "image=#{dom_id(article)}", data: {toggle: "modal", target: "#imgModal-#{dom_id(article)}"}) %>
                            <% elsif article.image %>
                                <span><%= link_to File.basename(article.image.url, ".*"), article.image.url, class: "pull-right article-image btn btn-primary" %></span>
                            <% end %>
                            <br><br>
                        </div>
                    <% end %>
                </div>
                <% if article.user_id == current_user.id %>
                    <div class="UIactions">                  
                        <span class="a"><%= button_to "Delete", article_path(article), method: :delete, data: { confirm: "are you sure you want to delete this article?"}, class: "btn btn-danger" %></span>
                        <span class="a"><%= link_to "Edit", edit_article_path(article), class: "btn btn-primary"%></span>
                        <% if current_user.admin? %>
                            <span class="a"><%= button_to "Pin this post", toggle_pinned_article_url(article.id), class: "btn btn-info" %></span>
                        <% end %>
                    </div>
                <% end %>
                <div id="imgModal-<%= dom_id(article) %>" class="modal fade">
                    <div class="modal-dialog">
                        <div class="model-content">
                            <div class="img modal-body">
                                <%= image_tag(article.image.url, class: "picture-modal-whole") if article.image?%>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        <% end %>
    <% end %>
    <br>
    <%= will_paginate @articles, renderer: BootstrapPagination::Rails %>
</div>

app/views/articles/new.html.erb
<h1 align="center" class="section-title">Write an Article</h1>
<%= render 'form' %>

app/views/articles/show.html.erb
<% if @article %>
    <div class="container">
        <div class="article-card">
                <div class="<%= @article.image? ? 'article card-body' : 'article card-body-no-image' %>">
                    <div class="col md-6">
                        <h4 class="card-title"><%= @article.title %></h4>
                        <% if @article.user %>
                            <small><p class="card-subtitle mb-2 text-muted">Created by: <%= link_to @article.user.username, user_path(@article.user) if @article.user_id %></p></small>
                        <% end %>
                        <%= @article.content.html_safe %>
                    </div>
                    <% if @article.image && @article.image.url %>
                        <div class="col md-6">
                            <% if @article.image && File.extname(@article.image.url).downcase.in?(['.jpg','.jpeg','.gif','.png']) %>
                                <%= image_tag(@article.image.url, alt: 'Image', :class => "pull-right article-image", id: "image=#{dom_id(@article)}", data: {toggle: "modal", target: "#imgModal-#{dom_id(@article)}"}) %>
                            <% elsif @article.image %>
                                <span><%= link_to File.basename(@article.image.url, ".*" ), @article.image.url, class: "pull-right article-image btn btn-primary" %></span>
                            <% end %>
                        </div>
                    <% end %>
                    <div id="imgModal-<%= dom_id(@article) %>" class="modal fade">
                        <div class="modal-dialog">
                            <div class="model-content">
                                <div class="img modal-body">
                                    <%= image_tag(@article.image.url, class: "picture-modal-whole") if @article.image?%>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
        </div>
        <div class="UIactions">
            <% if @article.user_id == current_user.id %>                   
                <span class="a"><%= button_to "Delete", article_path(@article), method: :delete, data: { confirm: "are you sure you want to delete this article?"}, class: "btn btn-danger" %></span>
                <span class="a"><%= link_to "Edit", edit_article_path(@article), class: "btn btn-primary"%></span>
            <% end %>
        </div>
        <br>
        <h3>Leave a Reply:</h3>
        <%= render partial: "comments/form", article_id: @article_id %>
        <% if @comments.any? %>
            <%= will_paginate @comments, renderer: BootstrapPagination::Rails %>
            <%= render partial: "comment" %>
        <% end %>
    </div>
<% end %>