config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      get '/articles/index'
      get '/users/index'
      get '/charts/index'

      post '/articles/create'
      post '/users/create'
      post '/charts/create'
      
      get '/articles/:id', to: 'articles#show'
      get '/users/:id', to: 'users#show'
      get '/pictures/:id', to: 'pictures#show'
      get '/charts/:id', to: 'chart#show'

      delete '/articles/destroy/:id', to: 'articles#destroy'
      delete '/charts/destroy/:id', to: 'charts#destroy'
      
      resources :users, only: [:create, :show, :index]
      resources :articles, only: [:create, :show, :index, :destroy]
      resources :charts, only: [:create, :show, :index, :destroy]
    end
  end
  
  get '/login', to: 'sessions#new', as: 'login'
  delete '/logout', to: 'sessions#destroy', as: 'logout'
  post '/login', to: 'sessions#create'
  get '/signup', to: 'users#new', as: 'signup'
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :users do
    member do
      get :confirm_email
      post :toggle_verified
    end
  end
  resources :search, only: [:index]
  resources :sessions, only: [:new, :create, :destroy]
  root 'pages#home'
  
  resources :cabin_attachments
  resources :articles do
    member do
      post :toggle_pinned
    end
  end
  resources :comments
  resources :events
  resources :cabins
  resources :cabindates
  resources :galleries
  resources :rooms
  resources :room_messages
  resources :charts

  get '/articles', to: 'articles#index'
  get '/blog', to: 'articles#index'
  get '/users', to: 'users#index'
  get '/search', to: 'pages#search', as: 'search'
  get '/forms', to: 'pages#forms', as: 'forms'
  get '/bylaws', to: 'pages#bylaws', as: 'bylaws'
  get '/chartiable_gift', to: 'pages#charitable_gift', as: 'charitable_gift'
  get '/customs', to: 'pages#customs', as: 'customs'
  get '/history', to: 'pages#history', as: 'history'
  get '/membership', to: 'pages#membership', as: 'membership'
  get '/planned_giving', to: 'pages#planned_giving', as: 'planned_giving'
  get '/familyagreements', to: 'pages#familyagreements', as: 'familyagreements'
  get '/archives', to: 'pages#archives', as: 'archives'
  get '/committee_primer', to: 'pages#committee_primer', as: 'committee_primer'

  match '*path' => 'pages#home', via: :all

end

app/models/user.rb
class User < ActiveRecord::Base
    extend FriendlyId
    attr_accessor :remember_token
    before_create :confirmation_token
    has_secure_password
    has_many :articles, dependent: :destroy
    has_many :comments, through: :articles
    has_many :events, dependent: :destroy
    has_many :cabins, dependent: :destroy
    has_many :galleries, dependent: :destroy
    has_many :events, dependent: :destroy
    has_many :charts, dependent: :destroy
    
    before_save { self.email = email.downcase }
  
    self.per_page = 20
    
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    VALID_PHONE_REGEX = /\A(\+\d{1,2}\s)?\(?\d{3}\)?[\s.-]\d{3}[\s.-]\d{4}\z/
    VALID_PASSWORD_REGEX = /\A(?=.{8,})(?=.*\d)(?=.*[a-z])(?=.*[A-Z])/x
    
    validates :email, presence: true, length: { maximum: 105 },
    uniqueness: { case_sensitive: false }, format: { with: VALID_EMAIL_REGEX}
    validates :username, presence: true, length: { minimum: 6, maximum: 20}
    validates :password, presence: true, format: { with: VALID_PASSWORD_REGEX }, on: :create
    validates :password, presence: true, format: { with: VALID_PASSWORD_REGEX }, on: :update, allow_nil: true

    friendly_id :username, use: :slugged
    
    def User.digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    def email_activate
      self.email_confirmed = true
      self.confirm_token = nil
      save!(:validate => false)
    end
  
    def send_password_reset
      generate_token(:password_reset_token)
      self.password_reset_sent_at = Time.zone.now
      save!
      UserMailer.password_reset(self).deliver
    end

    def User.new_token
      SecureRandom.urlsafe_base64
    end

    def remember
      self.remember_token = User.new_token
      update_attribute(:remember_digest, User.digest(remember_token))
    end

    def authenticated?(remember_token)
      return false if remember_digest.nil?
      BCrypt::Password.new(remember_digest).is_password?(remember_token)
    end
  
    def generate_token(column)
      begin
        self[column] = SecureRandom.urlsafe_base64.to_s
      end while User.exists?(column => self[column])
    end

    def forget
      update_attribute(:remember_digest, nil)
    end
  
    private
  
      def confirmation_token
        if self.confirm_token.blank?
          self.confirm_token = SecureRandom.urlsafe_base64.to_s
        end
      end
  end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
    def index
        user = User.all.except(
            :password, 
            :password_digest,
            :password_confirmation, 
            :password_reset_token,
            :admin
        )
        render json: user unless !logged_in?
    end

    def create
        user = User.create!(user_params) unless !logged_in?
        if user
            render json: user
        else
            render json: user.errors
        end
    end

    def show
        if user
            render json: user unless !logged_in?
        else
            render json: user.errors
        end
    end

    def destroy
        user&.destroy unless !logged_in?
        render json: { message: 'User deleted!'}
    end

    private

    def user_params
        params.require(:user).permit(:username, :firstname, :lastname, :email, :phone_number)
    end

    def user
        @user ||= User.find(params[:id])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:show, :edit, :update, :destroy]
    helper_method :require_user
    before_action :require_user, only: [:show, :edit, :update, :destroy, :index]
  
    def index
      @users = User.all.paginate(page: params[:page]).reorder('lastname ASC')
    end

    def show
    end
  
    def new
      @user = User.new
    end
  
    def edit
    end
  
    def create
      @user = User.new(user_params)
      respond_to do |format|
        if @user.save
          UserMailer.registration_confirmation(@user).deliver
          UserMailer.new_member_notification(@user).deliver
          flash[:notice] = "A registration link was just emailed to you. Please follow the link in your inbox to continue. If not in your main inbox, please check your spam folder."
          format.html { redirect_to root_url }
        else
          flash.now[:error] = "Something went wrong! Try again."
          format.html { render :new }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end
  
    def update
      respond_to do |format|
        if @user.update(user_params)
          format.html { redirect_to @user, notice: 'User was successfully updated.' }
          format.json { render :show, status: :ok, location: @user }
        else
          format.html { render :edit }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end
  
    def destroy
      @user.destroy
      respond_to do |format|
        format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  
    def confirm_email
      @user = User.find_by_confirm_token(params[:id])
      if @user
        @user.email_activate
        log_in @user
        flash[:success] = "Welcome to ICFC! Your email has been confirmed."
        redirect_to root_url
      else
        flash[:error] = "Sorry. User information does not exist."
        redirect_to root_url
      end
    end

    def toggle_verified
      set_user
      @user.toggle!(:verified)
      UserMailer.verified_confirmation(@user).deliver
      redirect_back(fallback_location: root_path)
    end
  
    private
      def set_user
        @user = User.friendly.find(params[:id])
      end
  
      def user_params
        params.require(:user).permit(:username, :firstname, :lastname, :email, :phone_number, :password, :password_confirmation, :confirm_token, :password_reset_token, :verified)
      end
  end

app/views/users/_form.html.erb
<div class="container user-form col-sm-offset-1">
    <%= form_with(model: user, local: true) do |form| %>
    <%= render 'layouts/error_messages', object: @user %>
    <div class="row">
        <div class="col-sm-3 user-names">
            <%= form.label :username %>
            <%= form.text_field :username, cols: "15", class: "form-control"  %>
        </div>
        <div class="col-sm-3 user-names">
            <%= form.label :firstname, "First Name" %>
            <%= form.text_field :firstname, class: "form-control"  %>
        </div>
        <div class="col-sm-3 user-names">
            <%= form.label :lastname, "Last Name" %>
            <%= form.text_field :lastname, class: "form-control"  %>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-5 user-contact">
            <%= form.label :email %>
            <%= form.text_field :email, class: "form-control"  %>
        </div>
        <div class="col-sm-4 user-contact">
            <%= form.label :phone_number %>
            <%= form.text_field :phone_number, placeholder: "(XXX) XXX-XXXX", class: "form-control"  %>
        </div>
    </div>
    <p><small>Password must:</small></p>
    <ul>
        <li><small>Be more than 8 characters</small></li>
        <li><small>Contain at least one digit</small></li>
        <li><small>Contain a lower case letter</small></li>
        <li><small>Contain an upper case letter </small></li>
    </ul>
    <div class="row">
        <div class="col-sm-9 form-group">
            <%= form.label :password %>
            <%= form.password_field :password, class: "form-control"  %>
        </div>
        <div class="col-sm-9 form-group">
            <%= form.label :password_confirmation %>
            <%= form.password_field :password_confirmation, class: "form-control"  %>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-9" align="center">
            <%= form.submit(@user.new_record?  ? "Sign up" : "Update account", class: 'btn btn-success btn-block') %>
            <% if !logged_in? && !current_user %>
                <p>Have an account? <%= link_to "Sign in here", login_path %></p>
            <% end %>
        </div>
    </div>
    <% end %>
</div>

app/views/users/edit.html.erb
<% if current_user.id == @user.id %>
    <div class="container">
        <h1>Edit information</h1>
        <div class="container user-form col-sm-offset-1">
            <%= form_with(model: @user, local: true) do |form| %>
            <%= render 'layouts/error_messages', object: @user %>
            <div class="row">
                <div class="col-sm-3 user-names">
                    <%= form.label :username %>
                    <%= form.text_field :username, cols: "15", class: "form-control"  %>
                </div>
                <div class="col-sm-3 user-names">
                    <%= form.label :firstname, "First Name" %>
                    <%= form.text_field :firstname, class: "form-control"  %>
                </div>
                <div class="col-sm-3 user-names">
                    <%= form.label :lastname, "Last Name" %>
                    <%= form.text_field :lastname, class: "form-control"  %>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-5 user-contact">
                    <%= form.label :email %>
                    <%= form.text_field :email, class: "form-control"  %>
                </div>
                <div class="col-sm-4 user-contact">
                    <%= form.label :phone_number %>
                    <%= form.text_field :phone_number, placeholder: "(XXX) XXX-XXXX", class: "form-control"  %>
                </div>
            </div>
            <br>
            <div class="row">
                <div class="col-sm-9" align="center">
                    <%= form.submit("Update account", class: 'btn btn-success btn-block') %>
                    <% if !logged_in? && !current_user %>
                        <p>Have an account? <%= link_to "Sign in here", login_path %></p>
                    <% end %>
                </div>
            </div>
            <% end %>
        </div>
    </div>
<% else %>
    <div class="container">
        <strong>You are not allowed to edit this user's information</strong>
    </div>
<% end %>

app/views/users/index.html.erb
<div class="container">
    <h1 align="center" class="section-title">Directory</h1>
    <%= link_to "edit profile", edit_user_path(current_user.id), class: "edit-user-btn btn btn-info btn-xs" %>
    <table class="users-table table">
        <thead>
            <th>Name</th>
            <th>Email Address</th>
            <th>Phone Number</th>
        </thead>
        <tbody>
        <%= will_paginate @users, renderer: BootstrapPagination::Rails %>
            <% @users.each do |user| %>
                <tr>
                    <td><%= link_to "#{user.firstname} #{user.lastname}", user_path(user) %></td>
                    <td><%= user.email %></td>
                    <td><%= number_to_phone(user.phone_number) %></td>
                    <td>
                    <% if current_user.admin %>
                        <span class="a">
                            <% if !user.verified %>
                                <%= button_to "Verify", toggle_verified_user_url(user.id), class: "btn-xs btn btn-warning" %>
                            <% elsif user.verified %>
                                <%= button_to "De-Verify", toggle_verified_user_url(user.id), class: "btn-xs btn btn-info" %>
                            <% end %>
                        </span>
                        <span class="a"><%= button_to "Delete", user_path(user), method: :delete, data: { confirm: "are you sure you want to delete this user?"}, class: "btn-xs btn btn-danger" %></span>
                    <% end %>
                    </td>
                </tr>
                <% will_paginate @users, renderer: BootstrapPagination::Rails %>
            <% end %>
        </tbody>
    </table>
</div>

app/views/users/new.html.erb
<div class="user-form container">
    <h1 class="section-title" align="center">New User Registration</h1>
    <%= render 'form', user: @user %>
</div>

app/views/users/show.html.erb
<%= content_tag :div,
    id: "session_id_tag",
    data: current_user.id.to_json do 
%>
<% end %>
<%= react_component("components/users/Show", 
  { data: current_user.id.to_json }) 
%>