config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      get '/articles/index'
      get '/users/index'
      get '/charts/index'

      post '/articles/create'
      post '/users/create'
      post '/charts/create'
      
      get '/articles/:id', to: 'articles#show'
      get '/users/:id', to: 'users#show'
      get '/pictures/:id', to: 'pictures#show'
      get '/charts/:id', to: 'chart#show'

      delete '/articles/destroy/:id', to: 'articles#destroy'
      delete '/charts/destroy/:id', to: 'charts#destroy'
      
      resources :users, only: [:create, :show, :index]
      resources :articles, only: [:create, :show, :index, :destroy]
      resources :charts, only: [:create, :show, :index, :destroy]
    end
  end
  
  get '/login', to: 'sessions#new', as: 'login'
  delete '/logout', to: 'sessions#destroy', as: 'logout'
  post '/login', to: 'sessions#create'
  get '/signup', to: 'users#new', as: 'signup'
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :users do
    member do
      get :confirm_email
      post :toggle_verified
    end
  end
  resources :search, only: [:index]
  resources :sessions, only: [:new, :create, :destroy]
  root 'pages#home'
  
  resources :cabin_attachments
  resources :articles do
    member do
      post :toggle_pinned
    end
  end
  resources :comments
  resources :events
  resources :cabins
  resources :cabindates
  resources :galleries
  resources :rooms
  resources :room_messages
  resources :charts

  get '/articles', to: 'articles#index'
  get '/blog', to: 'articles#index'
  get '/users', to: 'users#index'
  get '/search', to: 'pages#search', as: 'search'
  get '/forms', to: 'pages#forms', as: 'forms'
  get '/bylaws', to: 'pages#bylaws', as: 'bylaws'
  get '/chartiable_gift', to: 'pages#charitable_gift', as: 'charitable_gift'
  get '/customs', to: 'pages#customs', as: 'customs'
  get '/history', to: 'pages#history', as: 'history'
  get '/membership', to: 'pages#membership', as: 'membership'
  get '/planned_giving', to: 'pages#planned_giving', as: 'planned_giving'
  get '/familyagreements', to: 'pages#familyagreements', as: 'familyagreements'
  get '/archives', to: 'pages#archives', as: 'archives'
  get '/committee_primer', to: 'pages#committee_primer', as: 'committee_primer'

  match '*path' => 'pages#home', via: :all

end

app/models/room.rb
class Room < ApplicationRecord
    extend FriendlyId

    has_many :room_messages, dependent: :destroy, inverse_of: :room

    friendly_id :name, use: :slugged
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
    helper_method :require_user
    before_action :load_entities, :require_user
    
    def index
        @rooms = Room.all
    end

    def new
        @room = Room.new
    end

    def show
        @room_message = RoomMessage.new room: @room
        @room_messages = @room.room_messages.includes(:user)
    end

    def create
        @room = Room.new permitted_parameters
        if @room.save
            flash[:success] = "Room #{@room.name} was created successfully"
            redirect_to rooms_path
        else
            render :new
        end
    end

    def edit
    end

    def update
        if @room.update_attributes(permitted_parameters)
            flash[:success] = "Room #{@room.name} updated successfully"
            redirect_to rooms_path
        else
            render :new
        end
    end

    def destroy
        @room = Room.find(params[:id]) if params[:id]
        respond_to do |format|
            if @room.destroy
                format.html { redirect_to rooms_path, notice: "Room deleted" }
            else
                format.html { redirect_to rooms_path }
            end
        end
    end

    protected
     
        def load_entities
            @rooms = Room.all
            @room = Room.friendly.find(params[:id]) if params[:id]
        end

        def permitted_parameters
            params.require(:room).permit(:name)
        end
end

app/views/rooms/_form.html.erb
<div class="form-inline">
    <div class="row">
            <%= simple_form_for(@room, html: { multipart: true }) do |f| %>
            <div class="input-group rooms-form">
                <span class="input-group-addon" id="basic-addon1">
                    <%= f.text_field :name, placeholder: "Room Name", class: "form-control" %>
                </span>
                <span class="input-group-addon" id="basic-addon">
                    <%= f.button :submit, "Save", class: "btn btn-md btn-success", id: "room-save-btn" %>
                </span>
            </div>
        <% end %>
    </div>
</div>

app/views/rooms/_rooms.html.erb
<div class="sidebar rooms">
    <div class="sidebar-header">
        Rooms:
        <%= link_to new_room_path, class: "btn btn-success btn-xs pull-right" do %>
            <i class="fa fa-edit"></i>
        <% end %>
    </div>
    <% if @rooms %>
        <div class="rooms-list-wrapper">
            <% @rooms.each do |room| %>
                <li class="rooms-list"><%= link_to room.name, room_path(room), class: "room-link" %></li>
            <% end %>
        </div>
    <% end %>
</div>

app/views/rooms/edit.html.erb
<h1>
    Editing <%= @room.name %>
</h1>

<%= render partial: "form" %>

app/views/rooms/index.html.erb
<div class="container">
    <% if logged_in? && current_user %>
        <div class="row">
            <div class="col-12 col-md-3">
                <%= render partial: "rooms" %>
            </div>
        </div>
    <% else %>
        <h1>You must be logged in to view this page</h1>
    <% end %>
</div>

app/views/rooms/new.html.erb
<div class="container">
    <h1>
        Add a Room
    </h1>
    <%= render partial: "form" %>
</div>

app/views/rooms/show.html.erb
<div id="#rooms-show-container" class="container">
    <% if logged_in? && current_user %>
        <h1 class="room-title">
            <%= @room.name %>
        </h1>
        <hr>
        <div class="row">
            <div class="col-12 col-md-3">
                <%= render partial: "rooms" %>
            </div>
            <div class="chat-column">
                <div class="chat" data-channel-subscribe="room" data-room-id="<%= @room.id %>" >
                    <% @room_messages.each do |room_message| %>
                        <div class="chat-message-container">
                            <div class="row no-gutters">
                                <div class="col">
                                    <div class="message-content <%= room_message.user_id == current_user.id ? 'own-message' : 'other-message' %>">
                                        <small><em><%= room_message.user.username %>:</em></small>
                                        <%= room_message.message.html_safe %>
                                        <div class="text-right">
                                            <small>
                                                <span class="a">
                                                    <%= room_message.created_at.strftime('%Y/%m/%d at: %H:%M:%S') %>
                                                </span>
                                                <% if room_message.user_id == current_user.id %>
                                                    <span class="a"><%= button_to "Delete", room_message_path(room_message), method: :delete, data: { confirm: "Are you sure you want to delete this message?"}, class: "btn-xs btn btn-danger" %></span>
                                                <% end %>
                                            </small>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <% end %>
                </div>
                <%= simple_form_for @room_message, remote: true do |f| %>
                    <div class="chat-message">
                        <%= trix_editor :room_message, :message, as: :string, wrapper: false, label: false, input_html: { class: "chat-input" } %>
                        <%= button_tag class: "pt-3 btn btn-success btn-xs pull-right" do %>
                            Send Message
                        <% end %>
                    </div>
                    <%= f.input :room_id, as: :hidden %>
                <% end %>
            </div>
        </div>
        <div class="hidden">
            <div class="d-none" data-role="message-template">
                <div class="chat-message-container">
                    <div class="row no-gutters">
                        <div class="col">
                            <div class="message-content own-message">
                                <div data-role="message-text">
                                <div class="text-right">
                                    <small data-role="message-date"></small>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <% else %>
        <h1>You must be logged in to to see this page </h1>
    <% end %>
</div>